# Generated by Django 6.0.1 on 2026-04-16 08:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceattemptlog',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'Attempt Log'},
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-marked_at'], 'verbose_name': 'Attendance Record'},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Attendance Session'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code'], 'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'ordering': ['course__code'], 'verbose_name': 'Course Registration'},
        ),
        migrations.AlterModelOptions(
            name='devicebinding',
            options={'verbose_name': 'Device Binding'},
        ),
        migrations.AlterModelOptions(
            name='requestthrottlelog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Throttle Log'},
        ),
        migrations.AlterModelOptions(
            name='rotatingsessiontoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rotating Session Token'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='courseregistration',
            old_name='created_at',
            new_name='registered_at',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 16, 8, 42, 4, 45407, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendanceattemptlog',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceattemptlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_logs', to='attendance.attendancesession'),
        ),
        migrations.AlterField(
            model_name='attendanceattemptlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempt_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='device_fingerprint',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='devicebinding',
            name='fingerprint',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='rotatingsessiontoken',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='attendance_users', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Lecturer'), ('student', 'Student')], db_index=True, default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='attendance_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
